```yaml
project:
  type: website

website:
  title: "Atelier Conakry"
  site-url: "https://ousmanerabi.github.io/Atelier_Conakry"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - text: Sessions
        menu:
          - text: Jour 1 – Données spatiales
            href: jour1.qmd
          - text: Jour 2 – LISA
            href: jour2.qmd
          - text: Jour 3 – Scan spatial
            href: jour3.qmd
          - text: Analyse R
            href: 04_spatial_in_R.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

```
